# Generated by Django 6.0.2 on 2026-08-12 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productcategory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Product Category', 'verbose_name_plural': 'Product Categories'},
        ),
    ]
