# Generated by Django 6.0.2 on 2026-08-12 09:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import django_summernote.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_productcategory_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('logo', models.ImageField(upload_to='product/brand_image')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Product Brands',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='product/image')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='in BDT', max_digits=8, validators=[django.core.validators.MinValueValidator(0.0, "Product price can't less than 0")])),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, help_text='In percentage', max_digits=5, validators=[django.core.validators.MaxValueValidator(100, "Dsicount can't greater than 100"), django.core.validators.MinValueValidator(0, "Discount can't less than 0")])),
                ('stock', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('description', django_summernote.fields.SummernoteTextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ManyToManyField(blank=True, to='product.productcategory')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productbrand')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
