# Generated by Django 6.0.2 on 2026-08-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_productcategory_image_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productbrand',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
