# Generated by Django 6.0.2 on 2026-08-12 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productbrand_is_active_productcategory_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productbrand',
            options={'ordering': ['-created_at'], 'verbose_name': 'Product Brand', 'verbose_name_plural': 'Product Brands'},
        ),
    ]
