# Generated by Django 6.0.2 on 2026-08-12 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0003_customuser_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'ordering': ['user_type', '-created_at'], 'verbose_name': 'User'},
        ),
    ]
