# Generated by Django 6.0.2 on 2026-08-16 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_remove_cart_session_id_orderitem_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='total_amount',
            new_name='total_price',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='final_price',
            new_name='total_price',
        ),
    ]
