# Generated by Django 6.0.2 on 2026-08-24 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_orderitem_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='is_ordered',
        ),
    ]
