# Generated by Django 6.0.2 on 2026-08-26 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_alter_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_charge',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
